version: '3'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    env_file: production.env
    depends_on:
      - database

  nginx:
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: always
