version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'

  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - .:/app
    env_file: .env
    depends_on:
      - 'database'
    ports:
      - '9093:9093'
